### ISSUE TITLE
Route Post ne fonctionne pas, renvoie erreur serveur

### ISSUE THREAD

**Issue by murielralu** [murielralu/Exercice-Creation-API-Todo-Liste#1]
@enzoclock
Enzo,
J'ai créé une todoliste simple. 
Ma route post ne fonctionne pas : Insomnia m'indique : erreur serveur. Je n'ai pas d'erreur en console.
mon code mainController:
const mainController = { async createList(req, res) {
    try {
      const title = req.body.title;
      const importance = req.body.importance;
      if (!title || typeof title !== "string") {
        res.status(400).json({ error: "Missing or invalid body parameter: title" });
        return;
      }
      const createdList = await List.create({ title, importance });
      res.status(201).json(createdList);
    } catch (error) {
      res.status(500).json({ message: 'Erreur serveur' });
    }
  }}
Merci pour ton aide., mon repo est à jour.

**Comment by enzoclock** [comment]
@murielralu Rajoute un `console.error(error)` avant ta ligne du `res.status(500)` comme ca tu verras mieux ce qu'il se passe ! 

A vu de pied, je ne sais pas, j'attends de voir le message d'erreur. Tiens moi au courant

**Comment by murielralu** [comment]
@enzoclock Bon, j'ai du coup bien positionné la console.error et j'avais oublié de récupérer le contenu de ma liste.
Voilà l'erreur dans la console:
"original: error: une valeur NULL viole la contrainte NOT NULL de la colonne « importance_id » dans la relation « list »".
Peut être que je ne complète pas bien insomnia :
{
	"title": "Nettoyer extérieurs",
	"content": "Ramasser les feuilles",
	"name": "2"
}
Les routes GET fonctionnent.
Merci, A plus

**Comment by enzoclock** [comment]
Le problème c'est ton modèle de données : 

Tu as écris ça : 

https://github.com/murielralu/Exercice-Creation-API-Todo-Liste/blob/9bf44831511077d91ecf1f4a2e834f6e8e7f2451/back/data/create_tables.sql#L19C68-L19C68

➡️ `"importance_id" INTEGER NOT NULL REFERENCES "importance"("id"),`

Autrement dit, tu n'as PAS le droit de créer une liste si tu ne lui met pas une `importance_id` 

Alors que faire ?
- soit tu retires le `NOT NULL`
- soit quand tu créés ta liste, tu lui indiques obligatoirement une `importance_id` (=> donc entre autres, au niveau de ton controlleur et de ton appel via Insomnia)
